plugins {
    id 'java'
}

group = 'pl.marek.kingdomminions'
version = '1.0.27'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.129-stable'
    testImplementation 'io.papermc.paper:paper-api:26.2.build.129-stable'
    testImplementation platform('org.junit:junit-bom:5.14.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test { useJUnitPlatform() }

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

jar {
    archiveBaseName = 'KingdomMinions-Paper'
    manifest.attributes('Implementation-Version': project.version)
}













